### ISSUE TITLE
src7_AstsearchR_afterReCOIASのfindorb.pyが，MOIDsEaがないとのエラーで止まることがある

### ISSUE THREAD

**Issue by kn1cht** [COIAS-program/COIAS_program_github#6]
## 現象
先日，オリジナルCOIASのsugiura-nonmask-photometryブランチでの解析を試してみたところ，特定のデータについて次のようなエラーが出ました．

```
$ AstsearchR_afterReCOIAS
AstsearchR_afterReCOIAS begins
0% 10% 20% 30% 40% 50% 60% 70% 80% Some errors occur in findorb.py!
Traceback (most recent call last):
  File "/.../.../COIAS-program/COIAS_program_github/src7_AstsearchR_afterReCOIAS/findorb.py", line 205, in <module>
    findOrbResult = get_imformation_from_findorb_html(
  File "/.../.../COIAS-program/COIAS_program_github/src7_AstsearchR_afterReCOIAS/findorb.py", line 161, in get_imformation_from_findorb_html
    + MOIDsEa
UnboundLocalError: local variable 'MOIDsEa' referenced before assignment
```

## 暫定的な対処
`MOIDsEa`がないとのことで，`get_imformation_from_findorb_html()`関数のforループで`MOIDsEA`を設定できていないと考えられます．そこで，forループの外側で`MOIDsEA`に空文字列を入れるなどして変数が存在するようにすればエラーが出なくなりました．

## 原因の調査
直前のデータであるmpc7.txtの中でエラーが起きる測定データを1つずつ発見し， https://www.projectpluto.com/ に直接入力してみました．

- エラーが起きる測定
```
     H000020  C2016 08 28.33727 22 32 08.48 +03 03 42.25         23.7 i      T09
     H000020  C2016 08 28.34267 22 32 08.51 +03 03 42.20         24.1 i      T09
     H000020  C2016 08 28.35086 22 32 08.14 +03 03 41.38         23.8 i      T09
     H000020  C2016 08 28.35363 22 32 08.00 +03 03 39.92         23.8 i      T09
     H000020  C2016 08 28.35901 22 32 07.78 +03 03 37.84         24.1 i      T09
```

- エラーが起きない測定
```
     H000018  C2016 08 28.34267 22 32 35.69 +02 57 59.22         22.6 i      T09
     H000018  C2016 08 28.34816 22 32 35.39 +02 57 58.51         23.1 i      T09
     H000018  C2016 08 28.35086 22 32 35.30 +02 57 58.41         22.9 i      T09
     H000018  C2016 08 28.35901 22 32 34.88 +02 57 57.35         23.0 i      T09
```

返ってきたHTMLのコメント部を下図に示します．左がエラーの出たH000020，右が正常だったH000018です．
軌道要素の意味について詳しくは存じませんが，確かに左の測定では`MOIDs`の記載がないことが分かります．

![image](https://user-images.githubusercontent.com/16277200/233110796-b4db1d77-8026-48f9-aaec-4fd2d3565a42.png)

MOIDsがないことは不自然なのか（もし不自然だとすると，そのようなデータは弾くべきか），MOIDsは最終データに必ず記載されていた方がよいのかによって対処方法が変わると思いますので，ご確認頂けますでしょうか．

**Comment by kn1cht** [comment]
```     H000020  C2016 08 28.33727 22 32 08.48 +03 03 42.25         23.7 i      T09
     H000020  C2016 08 28.34267 22 32 08.51 +03 03 42.20         24.1 i      T09
     H000020  C2016 08 28.35086 22 32 08.14 +03 03 41.38         23.8 i      T09
     H000020  C2016 08 28.35363 22 32 08.00 +03 03 39.92         23.8 i      T09
     H000020  C2016 08 28.35901 22 32 07.78 +03 03 37.84         24.1 i      T09```

で，1行目～3行目で赤経の値が戻っているのがよろしくない気がしたので1行目だけを消してfindorbにかけてみると，今度はMOIDsが出ました

**Comment by kn1cht** [comment]
同じ画像，同じ天体で浦川さんが測定された結果を見るときれいに一直線に移動しており，MOIDsも算出できているので，こうしたデータが出たこと自体は私の操作ミスなどの可能性が高いです

**Comment by COIAS-program** [comment]
@kn1cht 
mainブランチの最新に、MOIDs: Eaが無くてもエラーを出さないようにしてみました。
おそらく大丈夫だと思うので、issueは閉じてしまいます。
もしお時間ありましたら、mainの最新でエラーが出た画像セットをもう一度解析してみて、エラーが出ず、MOIDs:Ea=NoData となっているか確認いただけましたら幸いです。
